# Generated by Django 4.2.4 on 2024-07-12 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boop_text', models.TextField(max_length=140, unique=True)),
                ('creation_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_foops', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
