# Generated by Django 4.2.4 on 2024-07-12 13:21

import TextRanker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0002_boop'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposableEmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[TextRanker.models.validate_not_disposable_email], verbose_name='email address'),
        ),
    ]
