# Generated by Django 4.2.4 on 2024-07-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0004_customuser_account_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ban_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for account ban'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_banned',
            field=models.BooleanField(default=False, help_text='If this is true, user has been banned for cause after review by admin', verbose_name='Account banned?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_under_review',
            field=models.BooleanField(default=False, help_text='This will be true when a ticket listing by this user has been reported', verbose_name='Account under review?'),
        ),
    ]
