# Generated by Django 4.2.4 on 2024-07-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0006_eventregion_eventtype_eventtypedetail_helpmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtypedetail',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.eventtype'),
            preserve_default=False,
        ),
    ]
