# Generated by Django 4.2.4 on 2024-07-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0007_eventtypedetail_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregion',
            name='region_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventregion',
            name='region_nickname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventregion',
            name='region_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
