# Generated by Django 4.2.4 on 2024-07-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0009_alter_ticketlisting_price_drop_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ticket_listing_photos/')),
                ('ticket_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='TextRanker.ticketlisting')),
            ],
        ),
    ]
