# Generated by Django 4.2.4 on 2024-07-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0010_ticketlistingphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlisting',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
