# Generated by Django 4.2.4 on 2024-07-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0012_rename_number_of_tickets_ticketlisting_original_qty_tickets_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketlisting',
            old_name='current_price',
            new_name='current_unit_price',
        ),
        migrations.RenameField(
            model_name='ticketlisting',
            old_name='current_price_currency',
            new_name='current_unit_price_currency',
        ),
        migrations.RenameField(
            model_name='ticketlisting',
            old_name='max_price',
            new_name='max_unit_price',
        ),
        migrations.RenameField(
            model_name='ticketlisting',
            old_name='max_price_currency',
            new_name='max_unit_price_currency',
        ),
        migrations.RenameField(
            model_name='ticketlisting',
            old_name='min_price',
            new_name='min_unit_price',
        ),
        migrations.RenameField(
            model_name='ticketlisting',
            old_name='min_price_currency',
            new_name='min_unit_price_currency',
        ),
    ]
