# Generated by Django 4.2.4 on 2024-07-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0014_ticketlisting_current_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
