# Generated by Django 4.2.4 on 2024-07-14 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0015_ticketpurchase_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='buyer_confirmed_received_tickets',
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='seller_confirmed_sent_tickets_datetime',
            field=models.DateTimeField(blank=True, help_text='Time that the seller confirmed tickets sent to buyer.', null=True),
        ),
        migrations.CreateModel(
            name='TransferConfirmationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='transfer_confirmation_photos/')),
                ('ticket_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='TextRanker.ticketpurchase')),
            ],
        ),
    ]
