# Generated by Django 4.2.4 on 2024-07-14 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0016_remove_ticketpurchase_buyer_confirmed_received_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlisting',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='slug',
        ),
        migrations.AlterField(
            model_name='ticketlisting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
