# Generated by Django 4.2.4 on 2024-07-14 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0017_remove_ticketlisting_slug_remove_ticketpurchase_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlisting',
            name='general_admission',
        ),
        migrations.RemoveField(
            model_name='ticketlisting',
            name='physical_ticket',
        ),
        migrations.RemoveField(
            model_name='ticketlisting',
            name='seats_description',
        ),
        migrations.RemoveField(
            model_name='ticketlisting',
            name='standing_only',
        ),
        migrations.AlterField(
            model_name='ticketlisting',
            name='tickets_description',
            field=models.TextField(blank=True, help_text='Please provide a description of the ticket(s) you are selling.', null=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_description', models.CharField(blank=True, help_text="If relevant, provide additional details of where the seats are. For example: 'Section 23 seat F'.", max_length=50, null=True)),
                ('physical_ticket', models.BooleanField(default=False, help_text='If this is a physical (non-digital) ticket, check this box.', verbose_name='Physical ticket?')),
                ('general_admission', models.BooleanField(default=False, help_text='If there are no assigned seats for this event, check this box.', verbose_name='General Admission?')),
                ('standing_only', models.BooleanField(default=False, help_text='If there are no seats at this event, check this box.', verbose_name='Standing room only?')),
                ('ticket_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TextRanker.ticketlisting')),
            ],
        ),
    ]
