# Generated by Django 4.2.4 on 2024-07-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0018_remove_ticketlisting_general_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.ticketpurchase'),
            preserve_default=False,
        ),
    ]
