# Generated by Django 4.2.4 on 2024-07-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0022_alter_ticket_ticket_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlistingreport',
            name='reported_by_email',
        ),
        migrations.AlterField(
            model_name='ticketlistingreport',
            name='report_reason',
            field=models.CharField(choices=[('Inauthentic', 'Listing seems fake'), ('Inappropriate', 'Listing has offensive content'), ('Incorrect', 'Listing appears to have incorrect information'), ('Other', 'Other')], max_length=20),
        ),
    ]
