# Generated by Django 4.2.4 on 2024-07-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0023_remove_ticketlistingreport_reported_by_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text="Link to the event's location on Google Maps", null=True),
        ),
    ]
