# Generated by Django 4.2.4 on 2024-07-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0024_venue_google_maps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='ticket_transfer_details',
            field=models.TextField(blank=True, help_text='Details of the account to transfer the tickets to.', null=True),
        ),
    ]
