# Generated by Django 4.2.4 on 2024-07-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0025_ticketpurchase_ticket_transfer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='seller_cancelled_transaction_note',
            field=models.TextField(blank=True, help_text='Reason seller was not able to transfer tickets.', null=True),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='seller_needed_more_transfer_details',
            field=models.TextField(blank=True, help_text='If seller was not given all details needed to transfer tickets.', null=True),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='status',
            field=models.CharField(choices=[('Ticket(s) in Cart', 'Ticket(s) in Cart'), ('Awaiting Payment Clearance', 'Awaiting Payment Clearance'), ('Awaiting Buyer Transfer Details', 'Awaiting Buyer Transfer Details'), ('Awaiting Ticket Transfer', 'Awaiting Ticket Transfer'), ('Voided by Customer Service', 'Voided by Customer Service'), ('Cancelled by Seller', 'Cancelled by Seller'), ('Finalized', 'Finalized')], max_length=35),
        ),
    ]
