# Generated by Django 4.2.4 on 2024-07-16 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0026_ticketpurchase_seller_cancelled_transaction_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOriginalPurchaseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TicketTransferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_transfer_details', models.TextField(help_text='Account email, username, first name, last name, or any other details needed for a seller to transfer tickets to this type of account.')),
                ('purchase_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.ticketoriginalpurchaselocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ticketlisting',
            name='original_purchase_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.ticketoriginalpurchaselocation'),
        ),
    ]
