# Generated by Django 4.2.4 on 2024-07-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0027_ticketoriginalpurchaselocation_tickettransferdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregion',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Link to the location on Google Maps', null=True),
        ),
    ]
