# Generated by Django 4.2.4 on 2024-07-17 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0029_ticketoriginalpurchaselocation_ticket_transfer_help_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlisting',
            name='original_purchase_location',
            field=models.ForeignKey(help_text='On what platform did you purchase your ticket(s)?', on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.ticketoriginalpurchaselocation'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
