# Generated by Django 4.2.4 on 2024-07-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0031_emailverification_verified_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlisting',
            name='status',
            field=models.CharField(choices=[('Live', 'Live'), ('Cancelled', 'Cancelled - Listing taken down by seller'), ('Listed - Verif. Hold', 'Listed - hold for ticket verification by seller'), ('Listed - Verif. Expired', 'Listed - Seller failed to verify ticket in time'), ('In Cart - Checkout Hold', 'In Cart - Hold for prospective buyer in checkout process'), ('On Hold - Reported Hold', 'On Hold - Hold due to listing reported'), ('Force Removed', 'Removed by staff due to violation of policy'), ('Sold - Awaiting Transfer', 'Sold - Awaiting ticket transfer'), ('Sold', 'Ticket sold successfully'), ('Unsold', 'Ticket not sold before event start time')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='status',
            field=models.CharField(choices=[('Ticket(s) in Cart', 'Ticket(s) in Cart'), ('Sold - Awaiting Buyer Transfer Details', 'Sold - Awaiting Buyer Transfer Details'), ('Sold - Awaiting Ticket Transfer', 'Sold - Awaiting Ticket Transfer'), ('Voided by Customer Service', 'Voided by Customer Service'), ('Cancelled by Seller', 'Cancelled by Seller'), ('Sold - Finalized', 'Sold - Finalized')], max_length=50),
        ),
    ]
