# Generated by Django 4.2.4 on 2024-07-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0035_alter_ticketlisting_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='status',
            field=models.CharField(choices=[('Ticket(s) in Cart', 'Ticket(s) in Cart'), ('Sold - Awaiting Buyer Transfer Details', 'Sold - Awaiting Buyer Transfer Details'), ('Sold - Awaiting Ticket Transfer', 'Sold - Awaiting Ticket Transfer'), ('Sold - Awaiting Payment Transfer to Seller', 'Sold - Awaiting Payment Transfer to Seller'), ('Voided by Customer Service', 'Voided by Customer Service'), ('Cancelled - Items no longer Available', 'Cancelled - Items no longer Available'), ('Ticket Transfer Issue - Seller Fault', 'Ticket Transfer Issue - Seller Fault'), ('Ticket Transfer Issue - Buyer Fault', 'Ticket Transfer Issue - Buyer Fault'), ('Sold - Finalized', 'Sold - Finalized')], max_length=50),
        ),
    ]
