# Generated by Django 4.2.4 on 2024-07-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0036_alter_ticketpurchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlisting',
            name='event_datetime',
            field=models.DateTimeField(verbose_name='Event Date/Time'),
        ),
        migrations.AlterField(
            model_name='ticketlisting',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
    ]
