# Generated by Django 4.2.4 on 2024-07-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0037_alter_ticketlisting_event_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_live',
            field=models.BooleanField(default=True, help_text='Is this ticket still available for purchase?'),
        ),
        migrations.AlterField(
            model_name='ticketlisting',
            name='original_purchase_location',
            field=models.ForeignKey(help_text='On what platform did you purchase your ticket(s)?', on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.ticketoriginalpurchaselocation', verbose_name='Original Ticket Vendor'),
        ),
        migrations.AlterField(
            model_name='ticketlisting',
            name='tickets_description',
            field=models.TextField(blank=True, help_text='Please provide a description of the ticket(s) you are selling.', null=True, verbose_name='Ticket(s) Description'),
        ),
    ]
