# Generated by Django 4.2.4 on 2024-07-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0039_alter_ticketpurchase_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ban_removal_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and time account ban to be removed'),
        ),
    ]
