# Generated by Django 4.2.4 on 2024-07-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0042_ticketpurchase_selling_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlistingreport',
            name='reported_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='helpmessage',
            name='help_message',
            field=models.TextField(help_text='Describe your question, concern, or request.'),
        ),
    ]
