# Generated by Django 4.2.4 on 2024-07-19 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0043_ticketlistingreport_reported_by_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHelpFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('help_type', models.CharField(choices=[('Refund request', 'Refund request'), ('Site Feedback', 'General site feedback'), ('Help', 'Help with using site'), ('City Request', 'Request to expand to my area'), ('Other', 'Other')], max_length=20)),
                ('help_message', models.TextField(help_text='Describe your question, concern, or request.')),
                ('submitted_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsed', models.BooleanField(default=False, help_text='Responded to request?')),
                ('responded_datetime', models.DateTimeField(blank=True, help_text='Time of response', null=True)),
                ('response_message', models.TextField(blank=True, help_text='Response to requestor', null=True)),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HelpMessage',
        ),
    ]
