# Generated by Django 4.2.4 on 2024-07-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0044_sitehelpfeedback_delete_helpmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitehelpfeedback',
            old_name='responsed',
            new_name='responded',
        ),
    ]
