# Generated by Django 4.2.4 on 2024-07-23 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0045_rename_responsed_sitehelpfeedback_responded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlisting',
            name='smart_pricing',
        ),
    ]
