# Generated by Django 4.2.4 on 2024-07-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0047_remove_ticketlisting_price_drop_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlisting',
            name='age_restriction',
            field=models.CharField(blank=True, help_text='If this event is age restricted, provide details of the allowed ages here.', max_length=20, null=True),
        ),
    ]
