# Generated by Django 4.2.4 on 2024-07-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0049_remove_venue_latitude_remove_venue_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='verified',
            field=models.BooleanField(default=False, help_text='For on-the-fly additions to the list of venues by users. If the venue has not been verified by the staff, it should not be shown to other users as an option.'),
        ),
    ]
