# Generated by Django 4.2.4 on 2024-07-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0050_venue_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(max_length=50),
        ),
    ]
