# Generated by Django 4.2.4 on 2024-08-29 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0051_alter_venue_venue_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_in_neighborhood_rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ListingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desirability', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_url', models.CharField(max_length=255)),
                ('reviewed_today', models.BooleanField(default=False)),
                ('listing_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TextRanker.listingsite')),
                ('most_recent_item_from_search', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.building')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Sold', 'Sold')], max_length=10)),
                ('datetime_added', models.DateTimeField()),
                ('datetime_removed', models.DateTimeField(blank=True, null=True)),
                ('unit', models.CharField(max_length=10)),
                ('listing_link', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('availability_date', models.DateField()),
                ('square_footage', models.PositiveIntegerField()),
                ('view_natural_light_rating', models.PositiveSmallIntegerField()),
                ('floor_of_building', models.SmallIntegerField()),
                ('has_dishwasher', models.BooleanField(default=False)),
                ('has_in_unit_washer_dryer', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('quality_rating', models.PositiveSmallIntegerField()),
                ('value_rating', models.PositiveSmallIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.building')),
                ('listing_site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.listingsite')),
            ],
        ),
        migrations.CreateModel(
            name='UnitNotAvailableReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_submitted', models.DateTimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TextRanker.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitSucksReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('datetime_submitted', models.DateTimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TextRanker.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitType', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventtypedetail',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='sitehelpfeedback',
            name='user_account',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_listing',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_purchase',
        ),
        migrations.RemoveField(
            model_name='ticketlisting',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='ticketlisting',
            name='event_type_detail',
        ),
        migrations.RemoveField(
            model_name='ticketlisting',
            name='original_purchase_location',
        ),
        migrations.RemoveField(
            model_name='ticketlisting',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='ticketlisting',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='ticketlistingphoto',
            name='ticket_listing',
        ),
        migrations.RemoveField(
            model_name='ticketlistingreport',
            name='reported_by_account',
        ),
        migrations.RemoveField(
            model_name='ticketlistingreport',
            name='ticket_listing',
        ),
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='buyer_account',
        ),
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='ticket_listing',
        ),
        migrations.RemoveField(
            model_name='tickettransferdetails',
            name='purchase_location',
        ),
        migrations.RemoveField(
            model_name='tickettransferdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transferconfirmationphoto',
            name='ticket_purchase',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='region',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_type',
        ),
        migrations.DeleteModel(
            name='EventRegion',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='EventTypeDetail',
        ),
        migrations.DeleteModel(
            name='SiteHelpFeedback',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketListing',
        ),
        migrations.DeleteModel(
            name='TicketListingPhoto',
        ),
        migrations.DeleteModel(
            name='TicketListingReport',
        ),
        migrations.DeleteModel(
            name='TicketOriginalPurchaseLocation',
        ),
        migrations.DeleteModel(
            name='TicketPurchase',
        ),
        migrations.DeleteModel(
            name='TicketTransferDetails',
        ),
        migrations.DeleteModel(
            name='TransferConfirmationPhoto',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='VenueType',
        ),
        migrations.AddField(
            model_name='unit',
            name='unitType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.unittype'),
        ),
        migrations.AddField(
            model_name='search',
            name='unitType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.unittype'),
        ),
        migrations.AddField(
            model_name='savedunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TextRanker.unit'),
        ),
        migrations.AddField(
            model_name='savedunit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TextRanker.neighborhood'),
        ),
    ]
