# Generated by Django 4.2.4 on 2024-08-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0052_building_listingsite_neighborhood_savedunit_search_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='most_recent_item_from_search',
        ),
        migrations.AddField(
            model_name='search',
            name='last_item_note',
            field=models.TextField(default=1, help_text='This will help you know when to stop browsing on the search. When you hit the item that says this, STOP.'),
            preserve_default=False,
        ),
    ]
