# Generated by Django 4.2.4 on 2024-08-30 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0053_remove_search_most_recent_item_from_search_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='unitType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='searches', to='TextRanker.unittype'),
        ),
    ]
