# Generated by Django 4.2.4 on 2024-08-30 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0054_alter_search_unittype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='reviewed_today',
        ),
        migrations.AddField(
            model_name='search',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 13, 26, 55, 851579)),
            preserve_default=False,
        ),
    ]
