# Generated by Django 4.2.4 on 2024-08-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0055_remove_search_reviewed_today_search_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='floor_of_building',
        ),
    ]
