# Generated by Django 4.2.4 on 2024-08-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0056_remove_unit_floor_of_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='availability_date',
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
