# Generated by Django 4.2.4 on 2024-08-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0057_remove_unit_availability_date_alter_building_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_bad_floor_of_building',
            field=models.BooleanField(default=False, help_text='If basement, ground floor looking out onto street, or second floor looking out onto busy street.'),
        ),
    ]
