# Generated by Django 4.2.4 on 2024-08-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0058_unit_is_bad_floor_of_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='building',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='has_air_conditioning',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='has_dishwasher',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='has_in_unit_washer_dryer',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_bad_floor_of_building',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='square_footage',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='view_natural_light_rating',
        ),
        migrations.AlterField(
            model_name='unit',
            name='value_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
