# Generated by Django 4.2.4 on 2024-08-31 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0059_remove_unit_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.neighborhood'),
            preserve_default=False,
        ),
    ]
