# Generated by Django 4.2.4 on 2024-08-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0061_alter_unit_listing_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedunit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
