# Generated by Django 4.2.4 on 2024-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0062_alter_savedunit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='verified_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
