# Generated by Django 4.2.4 on 2024-09-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0067_alter_unit_listing_link_alter_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitnotavailablereport',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Dismissed', 'Dismissed'), ('Actioned', 'Actioned')], default='Open', max_length=10),
        ),
        migrations.AddField(
            model_name='unitsucksreport',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Dismissed', 'Dismissed'), ('Actioned', 'Actioned')], default='Open', max_length=10),
        ),
    ]
