# Generated by Django 4.2.4 on 2024-09-03 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0068_unitnotavailablereport_status_unitsucksreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_rating', models.PositiveSmallIntegerField()),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.unittype')),
            ],
            options={
                'unique_together': {('quality_rating', 'price_min', 'price_max')},
            },
        ),
    ]
