# Generated by Django 4.2.4 on 2024-09-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0069_qualityvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityValuePriceMinMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.unittype')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='qualityvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='qualityvalue',
            name='min_max',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TextRanker.qualityvaluepriceminmax'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='qualityvalue',
            unique_together={('quality_rating', 'min_max')},
        ),
        migrations.RemoveField(
            model_name='qualityvalue',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='qualityvalue',
            name='price_min',
        ),
    ]
