# Generated by Django 4.2.4 on 2024-09-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0070_qualityvaluepriceminmax_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qualityvaluepriceminmax',
            unique_together={('price_min', 'price_max', 'unit_type')},
        ),
    ]
