# Generated by Django 4.2.4 on 2024-09-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0072_alter_qualityvaluepriceminmax_price_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_rating', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='qualityvaluepriceminmax',
            options={'ordering': ['price_min']},
        ),
        migrations.AlterField(
            model_name='qualityvalue',
            name='quality_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.qualityrating'),
        ),
    ]
