# Generated by Django 4.2.4 on 2024-09-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0073_qualityrating_alter_qualityvaluepriceminmax_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityvalue',
            name='value_rating',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
