# Generated by Django 4.2.4 on 2024-09-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0074_qualityvalue_value_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_url',
            field=models.CharField(max_length=1000),
        ),
    ]
