# Generated by Django 4.2.4 on 2024-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0075_alter_search_search_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='unit',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
