# Generated by Django 4.2.4 on 2024-10-11 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0080_alter_unit_category_alter_unit_quality_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='desirability',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='city_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='TextRanker.cityregion'),
        ),
    ]
